baseURL = 'https://nerd-geek.com/'
languageCode = 'en-us'
title = 'Nerd-Geek.com'
theme = 'hugo-geekblog'
sectionPagesMenu = 'main'
googleAnalytics = "G-RHTJKJXTF6"

[services]
  [services.disqus]
    shortname = 'nerd-geek'